//
//  UIColor+Untitled.swift
//
//  Generated by Zeplin on 2/29/16.
//  Copyright (c) 2016 Roundware All rights reserved.
//

import UIKit

extension UIColor {
    class func DarkSkyBlueColor() -> UIColor {
        return UIColor(red: 74.0 / 255.0, green: 144.0 / 255.0, blue: 226.0 / 255.0, alpha: 1.0)
    }
    
    class func AppleGreenColor() -> UIColor {
        return UIColor(red: 126.0 / 255.0, green: 211.0 / 255.0, blue: 33.0 / 255.0, alpha: 1.0)
    }

    class func GreenishTeal85Color() -> UIColor {
        return UIColor(red: 57.0 / 255.0, green: 199.0 / 255.0, blue: 130.0 / 255.0, alpha: 0.85)
    }

    class func GreenishTeal65Color() -> UIColor {
        return UIColor(red: 57.0 / 255.0, green: 199.0 / 255.0, blue: 130.0 / 255.0, alpha: 0.65)
    }

    class func TealGreen35Color() -> UIColor {
        return UIColor(red: 43.0 / 255.0, green: 156.0 / 255.0, blue: 101.0 / 255.0, alpha: 0.35)
    }
    
    class func CrimsonColor() -> UIColor {
        return UIColor(red: 228.0 / 255.0, green: 43.0 / 255.0, blue: 43.0 / 255.0, alpha: 1.0)
    }

}
